server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: "always"
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true
          routes:
            #USER-SERVICE
            #create
            - id: user-service-create
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/users
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*),/$\{segment}
            #read
            - id: user-service-read
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*),/$\{segment}
                - AuthorizationHeaderFilter
            #login
            - id: user-service-login
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/login
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*),/$\{segment}

            #BOARD-SERVICE
            #create
            - id: board-service
              uri: lb://BOARD-SERVICE
              predicates:
                - Path=/board-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/board-service/(?<segment>.*),/$\{segment}
#            #read
#            - id: board-service-read
#              uri: lb://BOARD-SERVICE
#              predicates:
#                - Path=/board-service/**
#                - Method=GET
#              filters:
#                - RemoveRequestHeader=Cookie
#                - RewritePath=/board-service/(?<segment>.*),/$\{segment}
            #create
            - id: comment-service
              uri: lb://COMMENT-SERVICE
              predicates:
                - Path=/comment-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/comment-service/(?<segment>.*),/$\{segment}

token:
  secret: ${TOKEN_SECRET}